apiVersion: apps/v1
kind: Deployment
metadata:
  name: orion-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: orion-api
  template:
    metadata:
      labels:
        app: orion-api
    spec:
      containers:
        - name: orion-api
          image: orion-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
