"""
MIH-IIE v2.1 spec-aligned modules.

These files originate from the provided v2.1 spec bundle and are surfaced
as a cohesive namespace for validation and integration work.
"""

from .e8 import E8, _normalize_int_vec, _dot_scaled  # noqa: F401
from .coordination import (  # noqa: F401
    BellPair,
    EntanglementRegistry,
    MajoranaZeroMode,
    SimulatedBackend,
    establish_e8_network,
    initialize_0d_seed_array,
    verify_symmetry,
    find_independent_operations,
    schedule_braiding_sequence,
    establish_synchronization,
    TemporalMode,
)
from .eds import (  # noqa: F401
    FrameResult,
    ValidationState,
    SystemState,
    ConvergenceEvaluator,
    corruption_score,
    paradigm_shift_score,
    validate_frame_invariance,
    detect_state,
    detect_obfuscation,
    autonomous_correction_protocol,
    run_frames,
    FrameInvariantEDS,
    get_default_frames,
)
from .error_correction import (  # noqa: F401
    Stabilizer,
    Syndrome,
    ErrorLocation,
    CorrectionResult,
    construct_stabilizers,
    construct_stabilizers_for_subgraph,
    SyndromeMeasurer,
    MinimumWeightDecoder,
    error_correction_cycle,
    ErrorMonitor,
    ErrorStatistics,
)
from .holography import (  # noqa: F401
    BoundaryMeasurement,
    TensorNode,
    TensorNetwork,
    identify_boundary,
    measure_boundary,
    build_e8_tensor_network,
    reconstruct_bulk,
    compute_inference,
    HolographicStateProjector,
    boundary_measurements_to_dict,
    reconstruct_bulk_from_boundary,
    optimize_contraction_order,
)

__all__ = [
    "E8",
    "_normalize_int_vec",
    "_dot_scaled",
    "BellPair",
    "EntanglementRegistry",
    "MajoranaZeroMode",
    "SimulatedBackend",
    "establish_e8_network",
    "initialize_0d_seed_array",
    "verify_symmetry",
    "find_independent_operations",
    "schedule_braiding_sequence",
    "establish_synchronization",
    "TemporalMode",
    "FrameResult",
    "ValidationState",
    "SystemState",
    "ConvergenceEvaluator",
    "validate_frame_invariance",
    "detect_state",
    "detect_obfuscation",
    "autonomous_correction_protocol",
    "run_frames",
    "FrameInvariantEDS",
    "get_default_frames",
    "corruption_score",
    "paradigm_shift_score",
    "Stabilizer",
    "Syndrome",
    "ErrorLocation",
    "CorrectionResult",
    "construct_stabilizers",
    "construct_stabilizers_for_subgraph",
    "SyndromeMeasurer",
    "MinimumWeightDecoder",
    "error_correction_cycle",
    "ErrorMonitor",
    "ErrorStatistics",
    "BoundaryMeasurement",
    "TensorNode",
    "TensorNetwork",
    "identify_boundary",
    "measure_boundary",
    "build_e8_tensor_network",
    "reconstruct_bulk",
    "compute_inference",
    "HolographicStateProjector",
    "boundary_measurements_to_dict",
    "reconstruct_bulk_from_boundary",
    "optimize_contraction_order",
]
