name: AI GitHub Automation

on:
  workflow_dispatch:
  push:
    tags:
      - 'automation-*'

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    if: ${{ secrets.GH_TOKEN != '' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run AI Commit Script
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: python commit_file.py

  auto-pr:
    runs-on: ubuntu-latest
    if: ${{ secrets.GH_TOKEN != '' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run AI Pull Request Script
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: python create_pull_request.py

  auto-issues:
    runs-on: ubuntu-latest
    if: ${{ secrets.GH_TOKEN != '' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run AI Issue Handler
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: python respond_to_issue.py

  auto-merge:
    runs-on: ubuntu-latest
    if: ${{ secrets.GH_TOKEN != '' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run AI Auto-Merge
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: python auto_merge_pr.py
