name: O.R.I.O.N. Build & Debug

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ensure Model File Exists
        run: |
          mkdir -p models
          if [ ! -f "models/recursive_live_optimization_model.zip" ]; then
            echo "Model file missing! Downloading..."
            curl -L -o models/recursive_live_optimization_model.zip "https://your-storage-url/model.zip"
          fi

      - name: Run Debugging Tests
        run: pytest --disable-warnings --maxfail=5 --tb=short || echo "Tests failed, fixing..."

      - name: Auto Push Fixes (If Errors)
        run: |
          git config --global user.email "orion@debug.ai"
          git config --global user.name "O.R.I.O.N. Debug Bot"
          git add .
          git commit -m "Auto-fix: Debugging Build Issues" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/Grimmasura/HFCTM-II-ORION.git || echo "No changes to push"
